---
version: "3.7"
services:
  app:
    image: datagov/ckanext-datagovtheme:${CKAN_VERSION} # ensures docker-compose will rebuild the right image in case we change CKAN_VERSION
    build:
      context: .
      args:
        CKAN_VERSION: ${CKAN_VERSION}
    environment:
      CKAN_SQLALCHEMY_URL: ${CKAN_SQLALCHEMY_URL}
      CKAN_DATASTORE_WRITE_URL: ${CKAN_DATASTORE_WRITE_URL}
      CKAN_DATASTORE_READ_URL: ${CKAN_DATASTORE_READ_URL}
      CKAN_SOLR_URL: ${CKAN_SOLR_URL}
      CKAN_REDIS_URL: ${CKAN_REDIS_URL}
      CKAN_DATAPUSHER_URL: ${CKAN_DATAPUSHER_URL}  # datapusher is not really enabled
      CKAN__PLUGINS: ${CKAN__PLUGINS}
    working_dir: /app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
      - solr
    volumes:
      - .:/app
  db:
    image: ckan/ckan-postgres-dev:${CKAN_VERSION}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      CKAN_POSTGRES_DB: ${CKAN_POSTGRES_DB}
      CKAN_POSTGRES_USER: ${CKAN_POSTGRES_USER}
      CKAN_DATASTORE_POSTGRES_DB: ${CKAN_DATASTORE_POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis
  solr:
    image: ckan/ckan-solr-dev:${CKAN_VERSION}
