---
# This docker environment is considered legacy. This uses images built from
# catalog in order to test in an environment very close. Unfortunately, it
# creates an external dependency and breaks often and unexpectedly. This
# approach introduces additional variables in the tests (e.g. many additional
# CKAN extensions) that we are not trying to test and end up causing false
# positives or false negatives. The new approach is less coupled to catalog and
# instead uses "vanilla" CKAN images as much as possible, with as few
# dependencies as possible.
# TODO delete this after catalog is running CKAN 2.9
version: "3.2"
services:
  ckan:
    image: datagov/catalog.data.gov:latest
    env_file:
      - ckan_env
    depends_on:
      - db
      - solr
      - redis
    ports:
      - "5000:5000"
    volumes:
      - ckan_storage:/var/lib/ckan
      - .:/srv/app/src_extensions/datagovtheme
  db:
    image: datagov/catalog.data.gov.db
    ports:
      - "5432:5432"
    expose:
      - "5432"
  solr:
    image: datagov/catalog.data.gov.solr
    restart: always
    expose:
      - "8983"
  redis:
    image: redis:alpine

volumes:
  ckan_storage:
  pg_data:
  solr_data:
