---
name: Tests
on: [push]

jobs:
  lint-test:
    name: Lint + Test
    uses: gsa/data.gov/.github/workflows/ckan-test.yml@ckan-reusable-workflow
    with:
      ext_name: datagovtheme
      plugins: harvest datagovtheme
    secrets: inherit

  ui-test:
      name: UI Test
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v3
        - name: build
          run: make build
        - name: ui-test
          run: make ui-test
        - name: cypress-artifacs
          uses: actions/upload-artifact@v3
          if: failure()
          with:
            name: cypress-artifacts
            path: |
              ./e2e/cypress/screenshots/
              ./e2e/cypress/videos/
